name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please fill out the form below to help us understand your request.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: |
        A clear and concise description of what the problem is.
        Example: I'm always frustrated when [...]
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see
      placeholder: |
        A clear and concise description of what you want to happen.
        How should this feature work?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
      placeholder: |
        A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe a specific use case or scenario where this feature would be helpful
      placeholder: |
        Example: When I want to [...], I need to be able to [...]
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would be helpful
        - High - Important for my use case
        - Critical - Blocking my workflow
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or examples about the feature request here.
      placeholder: |
        - Screenshots or mockups
        - Examples from other tools
        - Related issues or discussions
    validations:
      required: false

  - type: checkboxes
    id: checks
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues to ensure this feature has not already been requested
          required: true
        - label: I have checked the documentation to see if this feature is already available
          required: true
        - label: I am willing to help implement this feature (if applicable)
          required: false
